# Generated by Django 3.1.3 on 2020-11-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('anons', models.CharField(default='', max_length=250, verbose_name='Ананонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('date', models.DateField(verbose_name='Дата и время публикации')),
            ],
        ),
    ]
